version: "3.9"

services:
    stream-queue:
        build:
            context: .
        image: stream-queue
        container_name: stream-queue
        restart: unless-stopped
        ports:
            - "8080:80"
